---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_license: accept
  log_level: debug

platforms:
  - name: centos/7

<%
  access_key = `cat ~/.aws/credentials | grep default -A2 | tail -n2 | awk '{print $3}' | tr '\n' ' '`.split(' ')
%>

suites:
  - name: default
    run_list:
      - recipe[remote_resource::_remote_resource_integration_fixture]
    attributes:
      aws_region: 'us-east-1'
      aws_access_key_id: "<%= access_key[0] %>"
      aws_secret_access_key: "<%= access_key[1] %>"