<%
access_key = `cat ~/.aws/credentials | grep default -A2 | tail -n2 | awk '{print $3}' | tr '\n' ' '`.split(' ')
%>
---
driver:
  name: docker

platforms:
  - name: centos
    driver_config:
      image: centos
      platform: rhel

suites:
  - name: default
    run_list:
      - recipe[remote_resource::_remote_resource_integration_fixture]
    attributes:
      aws_region: 'us-east-1'
      aws_access_key_id: "<%= access_key[0] %>"
      aws_secret_access_key: "<%= access_key[1] %>"