name             'remote_resource'
maintainer       'github1'
maintainer_email 'github1@github.com'
license          'MIT'
description      'Provides remote_resource resource'
long_description 'Provides remote_resource resource'
version          '1.0.9'
issues_url 'https://github.com/github1/remote-resource-cookbook/issues'
source_url 'https://github.com/github1/remote-resource-cookbook'
chef_version '>= 12.5' if respond_to?(:chef_version)
supports 'redhat'
supports 'windows'